### PR TITLE
Use up to date elasticsearch client

### PR DESCRIPTION
**Pull request by nWidart**
Use up to date elasticsearch client

### CODE REVIEW

**Comment by nWidart** [comment]
Oh well, breaking changes (duh), tests failing.

**Comment by dieterve** [comment]
Nice, I'll do some testing myself. I am surprised we only need a few changes to make it work for 2.0.

**Comment by nWidart** [comment]
Using it currently against data, with the 2.0 wrapper, until now everything works.

One thing though, the config sets the hosts 'manually', `setHosts()`, as before it could set the hosts plus the other configuration options.

There is also a `fromConfig()` method, but that one made my client crash. As I'm short on time, I didn't investigate further yet.
If this `fromConfig()` method can accept an array of configuration, including the hosts, then we'll have the same behaviour as before on 1.3

**Comment by dieterve** [comment]
@nWidart: thanks for setting me on my way, I implemented the 2.0 SDK. I needed to do some more changes to better represent the new concepts of elasticsearch 2.0.

It is released as version `0.4.0`.

**Comment by nWidart** [comment]
Awesome! Thank you :+1:

**Pull request closed without merging**
